### ISSUE TITLE
Define Metadata 

### ISSUE THREAD

**Issue by Invarchitect** [InvArch/InvArch#1]
IPTs are **multi-layer & multi-attribute** NFTs.

Users need to be able to tokenize their ideas in various formats.

Consider the different methods that people use to design and display their ideas.
(_Example: 3D Renderings/CAD, powerpoints/slideshows, PDFs, images, code, etc._)

**Comment by SHA888** [comment]
Would be a good idea to mint it on Ethereum network and bridge (possibly cross-chain transfer in the future) leveraging Substrate cross-chain message protocol.
