### ISSUE TITLE
$VArch Tokens

### ISSUE THREAD

**Issue by Invarchitect** [InvArch/InvArch#3]
Design sample $VArch token contract

What token standard will $VArch tokens be?
how will we mint them?
What are the costs for $VArch token generation?

**Comment by SHA888** [comment]
## My Proposal for Append to White paper
## Protocol Info
```
  Tokens
  Token decimals:
  VArch (VARCH): 12
  Base unit: “Plank"
  Balance type: utility and governance for DEV
  Total Fixed Supply of VARCH: 11,000,000
```
Fixed amount of VARCH (11,000,000) will be minted on genesis and distributed according to our token economic plan.
